#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

rackup: /var/lib/diaspora/diaspora/config.ru
pid: /var/run/thin/thin.pid
wait: 30
timeout: 600
log: /var/log/thin
max_conns: 1024
require: []

max_persistent_conns: 512
environment: production
servers: 5
daemonize: true
#chdir: /usr/applications/localhash/current
#socket: /tmp/thin.sock
port: 80
